# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sasha delly 
description: > # this means to ignore newlines until "baseurl:"
    Let's learn together. And when we die, at last, we would stop getting dumber.    
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sashadelly.github.io/" # the base hostname & protocol for your site
twitter_username: butulok 
github_username:  sdll

# Build settings
highlighter: rouge
markdown: kramdown
